[build-system]
# https://setuptools.pypa.io/en/latest/userguide/index.html
requires = ["setuptools >= 77.0.3"]
build-backend = "setuptools.build_meta"

[project]
dynamic = ["version", "readme"]

name = "xiepy"
description = "Xie's collection of Python tools and scripts"
requires-python = ">=3.14"
dependencies = [
    "colorlog>=6.12.0",
]
license = "GPL-3.0-only"
license-files = ["LICENSE"]
authors = [{ name = "xieyuen" }]

[project.urls]
Homepage = "https://github.com/xieyuen/xiepy"

[project.optional-dependencies]
mcdr = [
    "mcdreforged>=2.15.7",
]
scripts = [
    "jsonpath>=0.82.2",
    "requests>=2.34.2",
]

[[tool.uv.index]]
url = "https://mirrors.aliyun.com/pypi/simple"
default = true

[tool.setuptools.dynamic]
version = { attr = "xiepy.common.constants.VERSION_PYPI" }
readme = { file = ["README.md"], content-type = "text/markdown" }

[tool.setuptools.packages.find]
where = ["src"]
include = ["xiepy*"]
namespaces = false
